#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs..

# set autocompletion path
fpath=(
  /usr/local/share/zsh/site-functions
  $fpath
)

# for command like `bundle exec rake parallel:spec[2]`
setopt nonomatch

# hub
eval "$(hub alias -s)"

# rbenv
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init - zsh)"

# go
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin

# nodebrew
export PATH=$HOME/.nodebrew/current/bin:$PATH

# android
export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$ANDROID_HOME/bin:$PATH
export PATH=$ANDROID_HOME/platform-tools:$PATH

# curl
export PATH="/usr/local/opt/curl/bin:$PATH"

# Java
export PATH=$PATH:/Applications/"Android Studio.app"/Contents/jre/jdk/Contents/Home/bin
export JAVA_HOME=/Applications/"Android Studio.app"/Contents/jre/jdk/Contents/Home

export PATH=$PATH:/Users/mickamy/.ghq/github.com/flutter/flutter/bin

# iTerm2 shell integration
source ~/.iterm2_shell_integration.zsh

#
# alias
#

alias g='git'
alias ls='ls -FG'
alias ll='ls -altFG'
alias f='open .'
alias vi='vim'
alias zshrc='vi ~/.zshrc'
alias zprofile='vi ~/.zprofile'
alias be='bundle exec'

# docker
alias doc='docker-compose'
alias dos='docker-sync'
alias docker-gc='docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /etc:/etc spotify/docker-gc'
alias dogc='docker-gc'

# SourceTree
alias stree='/Applications/SourceTree.app/Contents/Resources/stree'

# remove merged branches on local
alias gitremovel="git branch --merged | grep -vE '^\*|master$|develop$' | xargs -I % git branch -d %"

# curl with header response
alias curl-header='curl -D - -s -o /dev/null'

# ghq look equivalent
alias glook='cd $(ghq list --full-path | peco)'

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/mickamy/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/mickamy/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
